### PR TITLE
Feat/test snippets

### PR DESCRIPTION
**Pull request by ngoc2210**

### CODE REVIEW

**Comment by ngoc2210** [comment]
I have currently made some test cases for some snippets. Can you please give me some feedback about it?

**Comment by d-krupke** [comment]
1. You don't need any fixtures. Just put the whole model into a single test.
2. Make it a complete test with `Solve()`. Value will not return a sensible result if you haven't solved the model.
3. You do not need to test CP-SAT, just the API. So checking proto is not necessary.

Here an example for a good test case:

```python
def test_simple_intvar_example():
   model = cp_model.CpModel()

   x = model.NewIntVar(0, 100, "x")
   y = model.NewIntVar(0, 100, "y")

   model.Add(x + y <= 30)
   model.Maximize(30 * x + 50 * y)

   solver = cp_model.CpSolver()
   status = solver.Solve(model)
   assert status == cp_model.OPTIMAL, "Should be optimal"

   assert solver.Value(x) == 0, "x is expected to be 0"
   assert solver.Value(y) == 30, "y is expected to be 30"
```

**Comment by d-krupke** [comment]
And you can split the tests into multiple files when they are not related.

**Comment by ngoc2210** [comment]
thanks a lot. I've just pushed another test case based on your example. I hope it would be the correct one.

**Comment by d-krupke** [comment]
Yes, this would actually be a useful test case. However, you can keep it much simpler. The primary purpose is to verify that the interface of CP-SAT is used correctly in the examples. Thus, you do not need to do anything complicated. You can really just extend the examples of the primer by model and solve such that you can verify there is no error in the usage of the interface.

**Comment by d-krupke** [comment]
Here kind of errors I want to catch with the tests:

* Changes in the naming of arguments. E.g., `model.NewIntervalVar( start=start_var, size=length_var, end=end_var, name="flexible_interval")` may change argument name `end` to `stop`. By running the tests automatically every two weeks, I would get a mail if the latest version of CP-SAT has breaking changes.
* `model.AddMultiplicationEquality(xyz, [x, y, z])  # xyz = x*y*z` had errors in my previous trials despite the documentation looking like it should work. I would useful to know if the support changes.

**Comment by ngoc2210** [comment]
many thanks for your feedbacks :))
I pushed two commits to check the naming of arguments in methods `NewIntervalVar` and `NewFixedSizedIntervalVar`.
I also found that the name of the method to create interval variable with fixed length is `NewFixedSizedIntervalVar`, instead of  `NewIntervalVar` in README file.

**Comment by ngoc2210** [comment]
I also pushed the test for the three constraints `model.AddMultiplicationEquality(xyz, [x, y, z])  # xyz = x*y*z`, `model.AddModuloEquality(x, y, 3)  # x = y % 3`, `model.AddDivisionEquality(x, y, z)  # x = y // z`, maybe I now understand what you mean the feasible solutions for the given constraints exist but the tool might not be able to find them and you want to observe if it can find the solutions in the future. Is this right?

**Comment by d-krupke** [comment]
This has happened in the past, which is why I want tests :)

**Comment by d-krupke** [comment]
I like the test_snippets/test_FixedSizedIntervalvar.py test :)

**Comment by ngoc2210** [comment]
I have changed ` model.AddMultiplicationEquality(xyz, [x, y, z])` to ` model.AddMultiplicationEquality(xyz, x, y, z)`.  Is this the same what you mean?

**Comment by d-krupke** [comment]
> I have changed ` model.AddMultiplicationEquality(xyz, [x, y, z])` to ` model.AddMultiplicationEquality(xyz, x, y, z)`. Is this the same what you mean?

I don't know. Does CP-SAT support this syntax now?

**Comment by ngoc2210** [comment]
no, it still doesn't work. 
I changed  (AddMultiplicationEquality(xyz, [x, y, z]) to AddMultiplicationEquality(xyz, x, y, z) because I thought that is what you mean here "For example, AddMultiplicationEquality changes to the same interface as AddDivisionEquality were instead of a list, I have to pass a,b,c. ".

**Comment by d-krupke** [comment]
> no, it still doesn't work. I changed (AddMultiplicationEquality(xyz, [x, y, z]) to AddMultiplicationEquality(xyz, x, y, z) because I thought that is what you mean here "For example, AddMultiplicationEquality changes to the same interface as AddDivisionEquality were instead of a list, I have to pass a,b,c. ".

Maybe I should have use a more explicit conjunctive here: "If it were to change". This is just a wild example of what could happen.

**Comment by ngoc2210** [comment]
ohh now i remember a little bit about english grammar, what i almost forgot  haha

**Comment by d-krupke** [comment]
I have already integrated a lot of the tests. Closing.

**Pull request closed without merging**
